/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backtest
         * @description Past storms replayed with what really sold: the sales lost, and how much nearby stock could have covered.
         *
         *     An upper bound, not a forecast.
         */
        get: operations["backtest_api_backtest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness. With ?deep=true it also checks the data connection (this wakes the warehouse, so keep probes sparse).
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inventory */
        get: operations["inventory_api_inventory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stores */
        get: operations["stores_api_stores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stores/{store_id}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Store Forecast */
        get: operations["store_forecast_api_stores__store_id__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storm-desk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Storm Desk
         * @description Plans from the live data. Read-only: it can suggest moves but never approves or changes anything.
         */
        post: operations["storm_desk_api_storm_desk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transfers */
        get: operations["transfers_api_transfers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_transfers_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Transfers
         * @description The plan as a spreadsheet (CSV). Read-only. Open it in a spreadsheet, or print it to PDF from the browser.
         */
        get: operations["export_transfers_api_transfers_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_transfers_reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers/{transfer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transfer */
        get: operations["transfer_api_transfers__transfer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/what-if": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * What If
         * @description Simulates a storm and what it would cost. Read-only: it changes no data and approves nothing.
         */
        post: operations["what_if_api_what_if_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveRequest */
        ApproveRequest: {
            /** Ids */
            ids: string[];
            /** Note */
            note?: string | null;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Answered */
            answered: boolean;
            table?: components["schemas"]["AskTable"] | null;
        };
        /** AskTable */
        AskTable: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: (string | number | null)[][];
        };
        /** BacktestStorm */
        BacktestStorm: {
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Event Name */
            event_name: string;
            /**
             * Lost Units
             * @description Units sold beyond the stock on hand when the storm started
             */
            lost_units: number;
            /** Lost Usd */
            lost_usd: number;
            /**
             * Protected Units
             * @description Lost units a nearby store with spare stock could have covered
             */
            protected_units: number;
            /** Protected Usd */
            protected_usd: number;
            /**
             * Share Protected
             * @description Protected sales as a share of lost sales
             */
            share_protected: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Stores */
            stores: number;
        };
        /** DayUnits */
        DayUnits: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Units */
            units: number;
            /** Weekday */
            weekday: string;
        };
        /** DebateTurn */
        DebateTurn: {
            /**
             * Agent
             * @description Which role spoke: Forecaster, Risk checker or Summary writer
             */
            agent: string;
            /** Message */
            message: string;
        };
        /** DecisionResult */
        DecisionResult: {
            /**
             * Action
             * @enum {string}
             */
            action: "APPROVED" | "REJECTED";
            /** Changed */
            changed: string[];
            /** Message */
            message: string;
            /** Skipped */
            skipped: string[];
        };
        /** DeskStep */
        DeskStep: {
            /** Result */
            result: string;
            /**
             * What
             * @description Plain-language description of what storm desk checked
             */
            what: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Mode */
            mode: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "starting" | "unavailable";
            /**
             * Warehouse
             * @enum {string}
             */
            warehouse: "ready" | "starting" | "unavailable" | "not_checked";
        };
        /** InventoryItem */
        InventoryItem: {
            /** Available */
            available: number;
            /** Days Of Cover */
            days_of_cover: number | null;
            /** On The Way */
            on_the_way: number;
            product: components["schemas"]["ProductRef"];
            /** Runs Low Day */
            runs_low_day: string | null;
            /** Spare Units */
            spare_units: number;
            /**
             * Status
             * @enum {string}
             */
            status: "RUNNING_LOW" | "EXTRA" | "OK";
            store: components["schemas"]["Ref"];
        };
        /** Me */
        Me: {
            /** Can Approve */
            can_approve: boolean;
            /**
             * Data Label
             * @description Set to 'sample' while the app shows sample data
             */
            data_label?: string | null;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "planner" | "admin";
        };
        /** NextAction */
        NextAction: {
            /** Button */
            button: string;
            /** Detail */
            detail: string;
            /** Path */
            path: string;
            /** Title */
            title: string;
        };
        /** Overview */
        Overview: {
            /** Alerts */
            alerts: components["schemas"]["WeatherAlert"][];
            /** As Of */
            as_of: string | null;
            next_action: components["schemas"]["NextAction"];
            next_alert: components["schemas"]["WeatherAlert"] | null;
            /** Pending Transfers */
            pending_transfers: number;
            /** Stores At Risk */
            stores_at_risk: number;
            /** Urgent Transfers */
            urgent_transfers: number;
            /**
             * Weather Source
             * @description demo means a demo storm is placed on the weather screens
             * @default live
             * @enum {string}
             */
            weather_source: "live" | "demo";
        };
        /** PlanChange */
        PlanChange: {
            /** As Of */
            as_of: string;
            /** Before Time */
            before_time: string;
            /** Before Version */
            before_version: number;
            /** Now Time */
            now_time: string;
            /** Now Version */
            now_version: number;
            /** Sentence */
            sentence: string;
            /** Shortage Stores Before */
            shortage_stores_before: number;
            /** Shortage Stores Now */
            shortage_stores_now: number;
            /** Units Short Before */
            units_short_before: number;
            /** Units Short Now */
            units_short_now: number;
        };
        /** ProductForecast */
        ProductForecast: {
            /** Available */
            available: number;
            /** Days */
            days: components["schemas"]["DayUnits"][];
            product: components["schemas"]["ProductRef"];
            /** Range High */
            range_high: number;
            /** Range Low */
            range_low: number;
            /** Runs Low Day */
            runs_low_day: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "RUNNING_LOW" | "EXTRA" | "OK";
            /** Total Units */
            total_units: number;
            /** Why */
            why: string;
        };
        /** ProductRef */
        ProductRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Name Plural */
            name_plural: string;
        };
        /** Ref */
        Ref: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** RejectRequest */
        RejectRequest: {
            /** Ids */
            ids: string[];
            /** Reason */
            reason: string;
            /**
             * Reason Code
             * @description Structured reason; the daily run learns from it
             */
            reason_code?: ("TRUCK_UNAVAILABLE" | "STORE_CLOSED" | "ALREADY_COVERED" | "ROUTE_TOO_SLOW" | "OTHER") | null;
        };
        /** StoreForecast */
        StoreForecast: {
            /** As Of */
            as_of: string | null;
            /** Products */
            products: components["schemas"]["ProductForecast"][];
            store: components["schemas"]["StoreSummary"];
            /** Weather */
            weather: components["schemas"]["WeatherDay"][];
            /**
             * Weather Source
             * @description demo means a demo storm is placed on this forecast's weather
             * @default live
             * @enum {string}
             */
            weather_source: "live" | "demo";
        };
        /** StoreSummary */
        StoreSummary: {
            /** City */
            city: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Readiness
             * @description Share of products with enough cover for the storm window, 0 to 100
             * @default 0
             */
            readiness: number;
            /**
             * Readiness Label
             * @description Ready, Watch or At risk
             * @default
             */
            readiness_label: string;
            /** Region */
            region: string;
            /** Running Low */
            running_low: number;
            /**
             * Storm Days
             * @description Forecast days with a storm or heavy rain
             * @default 0
             */
            storm_days: number;
        };
        /** StormDeskPlan */
        StormDeskPlan: {
            /** Answered */
            answered: boolean;
            /**
             * Debate
             * @description How the three roles arrived at the plan
             */
            debate?: components["schemas"]["DebateTurn"][];
            /** Message */
            message?: string | null;
            /**
             * Plan
             * @description The plan, one sentence per item
             */
            plan?: string[];
            /**
             * Steps
             * @description What storm desk checked, in order
             */
            steps?: components["schemas"]["DeskStep"][];
            /**
             * Transfers
             * @description Pending transfers the plan refers to
             */
            transfers?: components["schemas"]["Transfer"][];
        };
        /** StormDeskRequest */
        StormDeskRequest: {
            /** Goal */
            goal: string;
        };
        /** Transfer */
        Transfer: {
            /**
             * Co2 Kg
             * @description Estimated kg CO2e for the move. See carbon.py for the assumptions.
             * @default 0
             */
            co2_kg: number;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "High" | "Medium" | "Low";
            /** Created At */
            created_at: string | null;
            /** Decided At */
            decided_at?: string | null;
            /** Decided By */
            decided_by?: string | null;
            /** Distance Miles */
            distance_miles: number;
            from_store: components["schemas"]["Ref"];
            /** Headline */
            headline: string;
            /** Id */
            id: string;
            /** Note */
            note?: string | null;
            product: components["schemas"]["ProductRef"];
            /** Qty */
            qty: number;
            /** Reason */
            reason: string;
            /** Runs Low Day */
            runs_low_day: string | null;
            /** Sales Protected Usd */
            sales_protected_usd: number;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "APPROVED" | "REJECTED";
            to_store: components["schemas"]["Ref"];
            /**
             * Urgency
             * @enum {string}
             */
            urgency: "URGENT" | "NORMAL";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeatherAlert */
        WeatherAlert: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Detail */
            detail: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "storm" | "heavy_rain" | "heat";
            /** Stores */
            stores: string[];
            /** Title */
            title: string;
            /** Weekday */
            weekday: string;
        };
        /** WeatherDay */
        WeatherDay: {
            /** Condition */
            condition: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Label */
            label: string;
            /** Rain In */
            rain_in: number;
            /** Temp Max F */
            temp_max_f: number;
            /** Weekday */
            weekday: string;
            /** Wind Max Mph */
            wind_max_mph: number;
        };
        /** WhatIfRequest */
        WhatIfRequest: {
            /**
             * Days
             * @description How many days the storm lasts
             */
            days: number;
            /** Region */
            region?: ("Florida" | "Texas" | "California") | null;
            /**
             * Start Day
             * @description 0 means tomorrow
             */
            start_day: number;
            /**
             * Strength
             * @description How strong the storm is, 0 to 100
             */
            strength: number;
        };
        /** WhatIfResult */
        WhatIfResult: {
            /** Answered */
            answered: boolean;
            /**
             * Extra Demand Units
             * @default 0
             */
            extra_demand_units: number;
            /**
             * Extra Lost Usd
             * @default 0
             */
            extra_lost_usd: number;
            /** Message */
            message?: string | null;
            /**
             * Normal Units
             * @default 0
             */
            normal_units: number;
            plan_change?: components["schemas"]["PlanChange"] | null;
            /** Rows */
            rows?: components["schemas"]["WhatIfRow"][];
            /** Sentence */
            sentence?: string | null;
            /**
             * Stock To Move Units
             * @default 0
             */
            stock_to_move_units: number;
            /**
             * Storm Units
             * @default 0
             */
            storm_units: number;
            /** Window */
            window?: string | null;
        };
        /** WhatIfRow */
        WhatIfRow: {
            /** Extra Lost Usd */
            extra_lost_usd: number;
            /** Normal Units */
            normal_units: number;
            /** On Hand */
            on_hand: number;
            /** Product */
            product: string;
            /** Store */
            store: string;
            /** Storm Units */
            storm_units: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask_api_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_api_backtest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestStorm"][];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: {
                deep?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transfer"][];
                };
            };
        };
    };
    inventory_api_inventory_get: {
        parameters: {
            query?: {
                status?: ("RUNNING_LOW" | "EXTRA") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    overview_api_overview_get: {
        parameters: {
            query?: {
                weather?: "live" | "demo";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stores_api_stores_get: {
        parameters: {
            query?: {
                weather?: "live" | "demo";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    store_forecast_api_stores__store_id__forecast_get: {
        parameters: {
            query?: {
                weather?: "live" | "demo";
            };
            header?: never;
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreForecast"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    storm_desk_api_storm_desk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StormDeskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StormDeskPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transfers_api_transfers_get: {
        parameters: {
            query?: {
                status?: ("PENDING" | "APPROVED" | "REJECTED") | null;
                urgency?: ("URGENT" | "NORMAL") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transfer"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_transfers_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_transfers_api_transfers_export_get: {
        parameters: {
            query?: {
                status?: ("PENDING" | "APPROVED" | "REJECTED") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_transfers_reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transfer_api_transfers__transfer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transfer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transfer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    what_if_api_what_if_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatIfRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatIfResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
