/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness. With ?deep=true it also checks the data connection (this wakes the warehouse, so keep probes sparse).
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inventory */
        get: operations["inventory_api_inventory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stores */
        get: operations["stores_api_stores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stores/{store_id}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Store Forecast */
        get: operations["store_forecast_api_stores__store_id__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storm-desk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Storm Desk
         * @description Plans from the live data. Read-only: it can suggest moves but never approves or changes anything.
         */
        post: operations["storm_desk_api_storm_desk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transfers */
        get: operations["transfers_api_transfers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_transfers_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_transfers_reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers/{transfer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transfer */
        get: operations["transfer_api_transfers__transfer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveRequest */
        ApproveRequest: {
            /** Ids */
            ids: string[];
            /** Note */
            note?: string | null;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Answered */
            answered: boolean;
            table?: components["schemas"]["AskTable"] | null;
        };
        /** AskTable */
        AskTable: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: (string | number | null)[][];
        };
        /** DayUnits */
        DayUnits: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Units */
            units: number;
            /** Weekday */
            weekday: string;
        };
        /** DecisionResult */
        DecisionResult: {
            /**
             * Action
             * @enum {string}
             */
            action: "APPROVED" | "REJECTED";
            /** Changed */
            changed: string[];
            /** Message */
            message: string;
            /** Skipped */
            skipped: string[];
        };
        /** DeskStep */
        DeskStep: {
            /** Result */
            result: string;
            /**
             * What
             * @description Plain-language description of what storm desk checked
             */
            what: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Mode */
            mode: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "starting" | "unavailable";
            /**
             * Warehouse
             * @enum {string}
             */
            warehouse: "ready" | "starting" | "unavailable" | "not_checked";
        };
        /** InventoryItem */
        InventoryItem: {
            /** Available */
            available: number;
            /** Days Of Cover */
            days_of_cover: number | null;
            /** On The Way */
            on_the_way: number;
            product: components["schemas"]["ProductRef"];
            /** Runs Low Day */
            runs_low_day: string | null;
            /** Spare Units */
            spare_units: number;
            /**
             * Status
             * @enum {string}
             */
            status: "RUNNING_LOW" | "EXTRA" | "OK";
            store: components["schemas"]["Ref"];
        };
        /** Me */
        Me: {
            /** Can Approve */
            can_approve: boolean;
            /**
             * Data Label
             * @description Set to 'sample' while the app shows sample data
             */
            data_label?: string | null;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "planner" | "admin";
        };
        /** NextAction */
        NextAction: {
            /** Button */
            button: string;
            /** Detail */
            detail: string;
            /** Path */
            path: string;
            /** Title */
            title: string;
        };
        /** Overview */
        Overview: {
            /** Alerts */
            alerts: components["schemas"]["WeatherAlert"][];
            /** As Of */
            as_of: string | null;
            next_action: components["schemas"]["NextAction"];
            next_alert: components["schemas"]["WeatherAlert"] | null;
            /** Pending Transfers */
            pending_transfers: number;
            /** Stores At Risk */
            stores_at_risk: number;
            /** Urgent Transfers */
            urgent_transfers: number;
        };
        /** ProductForecast */
        ProductForecast: {
            /** Available */
            available: number;
            /** Days */
            days: components["schemas"]["DayUnits"][];
            product: components["schemas"]["ProductRef"];
            /** Range High */
            range_high: number;
            /** Range Low */
            range_low: number;
            /** Runs Low Day */
            runs_low_day: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "RUNNING_LOW" | "EXTRA" | "OK";
            /** Total Units */
            total_units: number;
            /** Why */
            why: string;
        };
        /** ProductRef */
        ProductRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Name Plural */
            name_plural: string;
        };
        /** Ref */
        Ref: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** RejectRequest */
        RejectRequest: {
            /** Ids */
            ids: string[];
            /** Reason */
            reason: string;
        };
        /** StoreForecast */
        StoreForecast: {
            /** As Of */
            as_of: string | null;
            /** Products */
            products: components["schemas"]["ProductForecast"][];
            store: components["schemas"]["StoreSummary"];
            /** Weather */
            weather: components["schemas"]["WeatherDay"][];
        };
        /** StoreSummary */
        StoreSummary: {
            /** City */
            city: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Region */
            region: string;
            /** Running Low */
            running_low: number;
        };
        /** StormDeskPlan */
        StormDeskPlan: {
            /** Answered */
            answered: boolean;
            /** Message */
            message?: string | null;
            /**
             * Plan
             * @description The plan, one sentence per item
             */
            plan?: string[];
            /**
             * Steps
             * @description What storm desk checked, in order
             */
            steps?: components["schemas"]["DeskStep"][];
            /**
             * Transfers
             * @description Pending transfers the plan refers to
             */
            transfers?: components["schemas"]["Transfer"][];
        };
        /** StormDeskRequest */
        StormDeskRequest: {
            /** Goal */
            goal: string;
        };
        /** Transfer */
        Transfer: {
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "High" | "Medium" | "Low";
            /** Created At */
            created_at: string | null;
            /** Decided At */
            decided_at?: string | null;
            /** Decided By */
            decided_by?: string | null;
            /** Distance Miles */
            distance_miles: number;
            from_store: components["schemas"]["Ref"];
            /** Headline */
            headline: string;
            /** Id */
            id: string;
            /** Note */
            note?: string | null;
            product: components["schemas"]["ProductRef"];
            /** Qty */
            qty: number;
            /** Reason */
            reason: string;
            /** Runs Low Day */
            runs_low_day: string | null;
            /** Sales Protected Usd */
            sales_protected_usd: number;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "APPROVED" | "REJECTED";
            to_store: components["schemas"]["Ref"];
            /**
             * Urgency
             * @enum {string}
             */
            urgency: "URGENT" | "NORMAL";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeatherAlert */
        WeatherAlert: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Detail */
            detail: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "storm" | "heavy_rain" | "heat";
            /** Stores */
            stores: string[];
            /** Title */
            title: string;
            /** Weekday */
            weekday: string;
        };
        /** WeatherDay */
        WeatherDay: {
            /** Condition */
            condition: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Label */
            label: string;
            /** Rain In */
            rain_in: number;
            /** Temp Max F */
            temp_max_f: number;
            /** Weekday */
            weekday: string;
            /** Wind Max Mph */
            wind_max_mph: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask_api_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: {
                deep?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transfer"][];
                };
            };
        };
    };
    inventory_api_inventory_get: {
        parameters: {
            query?: {
                status?: ("RUNNING_LOW" | "EXTRA") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    overview_api_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    stores_api_stores_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreSummary"][];
                };
            };
        };
    };
    store_forecast_api_stores__store_id__forecast_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreForecast"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    storm_desk_api_storm_desk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StormDeskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StormDeskPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transfers_api_transfers_get: {
        parameters: {
            query?: {
                status?: ("PENDING" | "APPROVED" | "REJECTED") | null;
                urgency?: ("URGENT" | "NORMAL") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transfer"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_transfers_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_transfers_reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transfer_api_transfers__transfer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transfer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transfer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
