/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analysis/charts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analysis Charts
         * @description Demand, stock, shortages, transfers and protected sales, for the chosen data source.
         */
        get: operations["analysis_charts_api_analysis_charts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backtest
         * @description Past storms replayed with what really sold: the sales lost, and how much nearby stock could have covered.
         *
         *     An upper bound, not a forecast.
         */
        get: operations["backtest_api_backtest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Briefing
         * @description The morning briefing: a few plain sentences from today's figures, for the chosen data source.
         */
        get: operations["briefing_api_briefing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/alert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demo Alert
         * @description Starts the demo email job. Databricks sends the email to the alert address. Planners only.
         */
        post: operations["demo_alert_api_demo_alert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness. With ?deep=true it also checks the data connection (this wakes the warehouse, so keep probes sparse).
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Impact
         * @description What the plan is worth: protected sales, estimated profit and carbon, the decisions made, and the timeline of updates.
         */
        get: operations["impact_api_impact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analysis
         * @description A plain analysis of your uploaded data. Needs the stores, products, sales and stock files.
         */
        get: operations["analysis_api_ingest_analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/charts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Upload Charts Route
         * @description Chart data about your uploads: sales and stock by day, cover by store, status counts, and what was loaded.
         */
        get: operations["upload_charts_route_api_ingest_charts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upload Checks */
        get: operations["upload_checks_api_ingest_checks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/demo/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Demo
         * @description Loads the four sample workbooks in order, then builds the plan. One click for a demo.
         */
        post: operations["load_demo_api_ingest_demo_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/drop/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Drop Now
         * @description Loads any files waiting in the drop folder now, instead of waiting for the next check.
         */
        post: operations["scan_drop_now_api_ingest_drop_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/economics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Economics */
        get: operations["get_economics_api_ingest_economics_get"];
        /**
         * Set Economics
         * @description Truck cost per mile and product margin, used for the estimated profit of the plan.
         */
        put: operations["set_economics_api_ingest_economics_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feeds */
        get: operations["feeds_api_ingest_feeds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/feeds/{feed}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Clear */
        delete: operations["clear_api_ingest_feeds__feed__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/feeds/{feed}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview */
        get: operations["preview_api_ingest_feeds__feed__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/feeds/{feed}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rows In
         * @description Send rows from another system as JSON. Same checks as a file upload.
         */
        post: operations["rows_in_api_ingest_feeds__feed__rows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/feeds/{feed}/template.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Template Xlsx
         * @description An Excel template. Store and product codes are dropdowns, filled from the stores and products you uploaded.
         */
        get: operations["template_xlsx_api_ingest_feeds__feed__template_xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/feeds/{feed}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_ingest_feeds__feed__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Plan
         * @description Builds the plan from your uploads. The planner's screens can then use them as "Your uploads".
         */
        post: operations["build_plan_api_ingest_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/plan/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan Status */
        get: operations["plan_status_api_ingest_plan_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inventory */
        get: operations["inventory_api_inventory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Loads
         * @description Moves waiting for a decision, grouped by route, with the truck trips that sharing a load would save. Suggestion only.
         */
        get: operations["loads_api_loads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/markdowns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Markdowns
         * @description Surplus stock that would not sell in time at full price, with a discount that adds cash. Suggestions only: nothing changes.
         */
        get: operations["markdowns_api_markdowns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/markdowns/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Markdown
         * @description A planner approves or rejects a markdown suggestion. Records the decision; nothing changes in the stores.
         */
        post: operations["decide_markdown_api_markdowns_decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/response/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Storm Draft
         * @description Drafts the storm response for the current storm warning. Idempotent: returns the open draft if there is one. Sends nothing.
         */
        post: operations["storm_draft_api_response_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/response/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Storm Draft Get */
        get: operations["storm_draft_get_api_response__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/response/{draft_id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Storm Decide
         * @description A planner approves the chosen moves and rejects the rest. The same approval path as every transfer.
         */
        post: operations["storm_decide_api_response__draft_id__decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stores */
        get: operations["stores_api_stores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stores/{store_id}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Store Forecast */
        get: operations["store_forecast_api_stores__store_id__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storm-desk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Storm Desk
         * @description Plans from the live data. Read-only: it can suggest moves but never approves or changes anything.
         */
        post: operations["storm_desk_api_storm_desk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transfers */
        get: operations["transfers_api_transfers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_transfers_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Transfers
         * @description The plan as a spreadsheet (CSV). Read-only. Open it in a spreadsheet, or print it to PDF from the browser.
         */
        get: operations["export_transfers_api_transfers_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_transfers_reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers/{transfer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transfer */
        get: operations["transfer_api_transfers__transfer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/what-if": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * What If
         * @description Simulates a storm and what it would cost. Read-only: it changes no data and approves nothing.
         */
        post: operations["what_if_api_what_if_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Analysis */
        Analysis: {
            /** As Of */
            as_of: string;
            /** By Store */
            by_store: components["schemas"]["AnalysisStore"][];
            /**
             * Items
             * @description The short and watch items, most urgent first
             */
            items: components["schemas"]["AnalysisItem"][];
            /** Pairs */
            pairs: number;
            /** Products */
            products: number;
            /** Sales Value Usd */
            sales_value_usd: number;
            /** Short */
            short: number;
            /** Sold Units */
            sold_units: number;
            /** Stock Value Usd */
            stock_value_usd: number;
            /** Stores */
            stores: number;
            /** Watch */
            watch: number;
            /** Window Days */
            window_days: number;
        };
        /** AnalysisItem */
        AnalysisItem: {
            /** Days Of Cover */
            days_of_cover: number | null;
            /** On Hand */
            on_hand: number;
            /** Product */
            product: string;
            /** Sales Value Usd */
            sales_value_usd: number;
            /** Sold Per Day */
            sold_per_day: number;
            /**
             * Status
             * @description Short (under 7 days), Watch (under 21 days), Plenty, or No sales
             */
            status: string;
            /** Stock Value Usd */
            stock_value_usd: number;
            /** Store */
            store: string;
        };
        /** AnalysisStore */
        AnalysisStore: {
            /** Short Items */
            short_items: number;
            /** Stock Value Usd */
            stock_value_usd: number;
            /** Store */
            store: string;
        };
        /** ApproveRequest */
        ApproveRequest: {
            /** Ids */
            ids: string[];
            /** Note */
            note?: string | null;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Answered */
            answered: boolean;
            table?: components["schemas"]["AskTable"] | null;
        };
        /** AskTable */
        AskTable: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: (string | number | null)[][];
        };
        /** BacktestStorm */
        BacktestStorm: {
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Event Name */
            event_name: string;
            /**
             * Lost Units
             * @description Units sold beyond the stock on hand when the storm started
             */
            lost_units: number;
            /** Lost Usd */
            lost_usd: number;
            /**
             * Protected Units
             * @description Lost units a nearby store with spare stock could have covered
             */
            protected_units: number;
            /** Protected Usd */
            protected_usd: number;
            /**
             * Share Protected
             * @description Protected sales as a share of lost sales
             */
            share_protected: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Stores */
            stores: number;
        };
        /** Briefing */
        Briefing: {
            /** Headline */
            headline: string;
            /** Lines */
            lines: string[];
        };
        /** ChangeSince */
        ChangeSince: {
            /** Last Plan At */
            last_plan_at: string | null;
            /** Moves Now */
            moves_now: number;
            /** Moves Then */
            moves_then: number | null;
        };
        /** ChecksResult */
        ChecksResult: {
            /** Sentences */
            sentences: string[];
        };
        /** ColumnInfo */
        ColumnInfo: {
            /** Choices */
            choices: string[];
            /** Help */
            help: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Required */
            required: boolean;
        };
        /** DayUnits */
        DayUnits: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Units */
            units: number;
            /** Weekday */
            weekday: string;
        };
        /** DebateTurn */
        DebateTurn: {
            /**
             * Agent
             * @description Which role spoke: Forecaster, Risk checker or Summary writer
             */
            agent: string;
            /** Message */
            message: string;
        };
        /** DecisionResult */
        DecisionResult: {
            /**
             * Action
             * @enum {string}
             */
            action: "APPROVED" | "REJECTED";
            /** Changed */
            changed: string[];
            /** Message */
            message: string;
            /** Skipped */
            skipped: string[];
        };
        /** DemoAlertResult */
        DemoAlertResult: {
            /** Message */
            message: string;
            /** Started */
            started: boolean;
        };
        /** DeskStep */
        DeskStep: {
            /** Result */
            result: string;
            /**
             * What
             * @description Plain-language description of what storm desk checked
             */
            what: string;
        };
        /** DraftDecision */
        DraftDecision: {
            /**
             * Approve Ids
             * @description The moves to approve. Every other move in the draft is rejected.
             */
            approve_ids?: string[];
            /**
             * Reason
             * @default Not needed for this storm.
             */
            reason: string;
        };
        /** DraftMove */
        DraftMove: {
            /** Co2 Kg */
            co2_kg: number;
            /** Distance Miles */
            distance_miles: number;
            /** Headline */
            headline: string;
            /** Id */
            id: string;
            /** Qty */
            qty: number;
            /** Reason */
            reason: string;
            /** Sales Protected Usd */
            sales_protected_usd: number;
            /** Urgency */
            urgency: string;
        };
        /** DropResult */
        DropResult: {
            /** Folder */
            folder: string;
            /** Loaded */
            loaded: string[];
        };
        /** EconomicsBody */
        EconomicsBody: {
            /**
             * Margin Pct
             * @description Share of sales that is profit, in percent
             */
            margin_pct: number;
            /**
             * Truck Cost Per Mile
             * @description What one truck trip costs per mile, in dollars
             */
            truck_cost_per_mile: number;
        };
        /** FeedInfo */
        FeedInfo: {
            /** Columns */
            columns: components["schemas"]["ColumnInfo"][];
            /** Feed */
            feed: string;
            /** Kept */
            kept: number;
            /** Refused */
            refused: number;
            /** Template */
            template: string;
            /** Title */
            title: string;
            /** Updated */
            updated: string | null;
            /** What */
            what: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Mode */
            mode: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "starting" | "unavailable";
            /**
             * Warehouse
             * @enum {string}
             */
            warehouse: "ready" | "starting" | "unavailable" | "not_checked";
        };
        /** Impact */
        Impact: {
            /** As Of */
            as_of: string | null;
            /** Assumptions */
            assumptions: string[];
            changes: components["schemas"]["ChangeSince"];
            headline: components["schemas"]["ImpactHeadline"];
            /** Source */
            source: string;
            /** Timeline */
            timeline: components["schemas"]["TimelineEvent"][];
        };
        /** ImpactHeadline */
        ImpactHeadline: {
            /** Approved */
            approved: number;
            /** Co2 Kg */
            co2_kg: number;
            /** Margin Usd */
            margin_usd: number;
            /** Moves */
            moves: number;
            /** Net Usd */
            net_usd: number;
            /** Pending */
            pending: number;
            /** Protected Usd */
            protected_usd: number;
            /** Rejected */
            rejected: number;
            /** Trucking Usd */
            trucking_usd: number;
        };
        /** InventoryItem */
        InventoryItem: {
            /** Available */
            available: number;
            /** Days Of Cover */
            days_of_cover: number | null;
            /** On The Way */
            on_the_way: number;
            product: components["schemas"]["ProductRef"];
            /** Runs Low Day */
            runs_low_day: string | null;
            /** Spare Units */
            spare_units: number;
            /**
             * Status
             * @enum {string}
             */
            status: "RUNNING_LOW" | "EXTRA" | "OK";
            store: components["schemas"]["Ref"];
        };
        /** LoadMove */
        LoadMove: {
            /** Id */
            id: string;
            /** Product */
            product: string;
            /** Qty */
            qty: number;
        };
        /** LoadRoute */
        LoadRoute: {
            /** From Store */
            from_store: string;
            /** Miles */
            miles: number;
            /** Moves */
            moves: components["schemas"]["LoadMove"][];
            /** Saved Kg */
            saved_kg: number;
            /** Saved Usd */
            saved_usd: number;
            /** To Store */
            to_store: string;
            /** Trips Now */
            trips_now: number;
            /** Trips Together */
            trips_together: number;
            /** Units */
            units: number;
        };
        /** Loads */
        Loads: {
            /** Cost Per Mile */
            cost_per_mile: number;
            /** Routes */
            routes: components["schemas"]["LoadRoute"][];
            /** Saved Kg */
            saved_kg: number;
            /** Saved Usd */
            saved_usd: number;
            /** Trips Now */
            trips_now: number;
            /** Trips Together */
            trips_together: number;
            /** Truck Units */
            truck_units: number;
        };
        /** MarkdownDecision */
        MarkdownDecision: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "APPROVED" | "REJECTED";
            /** Product Id */
            product_id: string;
            /** Store Id */
            store_id: string;
        };
        /** MarkdownSuggestion */
        MarkdownSuggestion: {
            /**
             * Assumption
             * @description How the estimate was made, so it can be checked
             */
            assumption: string;
            /** Clears All */
            clears_all: boolean;
            /** Current Price */
            current_price: number;
            /** Decided At */
            decided_at?: string | null;
            /** Decided By */
            decided_by?: string | null;
            /**
             * Decision
             * @description pending, approved or rejected by a planner
             * @default pending
             */
            decision: string;
            /**
             * Discount Pct
             * @description Suggested discount, 10 to 40 percent
             */
            discount_pct: number;
            /**
             * Extra Cash Usd
             * @description Cash expected over holding the stock at full price, an estimate
             */
            extra_cash_usd: number;
            /** New Price */
            new_price: number;
            /** Note */
            note: string;
            product: components["schemas"]["ProductRef"];
            /**
             * Spare Units
             * @description Stock the store will not need in the week ahead
             */
            spare_units: number;
            store: components["schemas"]["Ref"];
            /**
             * Units Cleared
             * @description Units expected to sell in the clearance window at this discount
             */
            units_cleared: number;
        };
        /** Me */
        Me: {
            /** Can Approve */
            can_approve: boolean;
            /**
             * Data Label
             * @description Set to 'sample' while the app shows sample data
             */
            data_label?: string | null;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "planner" | "admin";
        };
        /** NextAction */
        NextAction: {
            /** Button */
            button: string;
            /** Detail */
            detail: string;
            /** Path */
            path: string;
            /** Title */
            title: string;
        };
        /** Overview */
        Overview: {
            /** Alerts */
            alerts: components["schemas"]["WeatherAlert"][];
            /** As Of */
            as_of: string | null;
            next_action: components["schemas"]["NextAction"];
            next_alert: components["schemas"]["WeatherAlert"] | null;
            /** Pending Transfers */
            pending_transfers: number;
            /** Stores At Risk */
            stores_at_risk: number;
            /** Urgent Transfers */
            urgent_transfers: number;
            /**
             * Weather Source
             * @description demo means a demo storm is placed on the weather screens
             * @default live
             * @enum {string}
             */
            weather_source: "live" | "demo";
        };
        /** PlanChange */
        PlanChange: {
            /** As Of */
            as_of: string;
            /** Before Time */
            before_time: string;
            /** Before Version */
            before_version: number;
            /** Now Time */
            now_time: string;
            /** Now Version */
            now_version: number;
            /** Sentence */
            sentence: string;
            /** Shortage Stores Before */
            shortage_stores_before: number;
            /** Shortage Stores Now */
            shortage_stores_now: number;
            /** Units Short Before */
            units_short_before: number;
            /** Units Short Now */
            units_short_now: number;
        };
        /** PlanStatus */
        PlanStatus: {
            /** As Of */
            as_of?: string | null;
            /** Net Benefit */
            net_benefit?: {
                [key: string]: number;
            } | null;
            /** Ready */
            ready: boolean;
            /** Summary */
            summary?: {
                [key: string]: unknown;
            } | null;
        };
        /** ProductForecast */
        ProductForecast: {
            /** Available */
            available: number;
            /** Days */
            days: components["schemas"]["DayUnits"][];
            product: components["schemas"]["ProductRef"];
            /** Range High */
            range_high: number;
            /** Range Low */
            range_low: number;
            /** Runs Low Day */
            runs_low_day: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "RUNNING_LOW" | "EXTRA" | "OK";
            /** Total Units */
            total_units: number;
            /** Why */
            why: string;
        };
        /** ProductRef */
        ProductRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Name Plural */
            name_plural: string;
        };
        /** Ref */
        Ref: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** Refusal */
        Refusal: {
            /** Line */
            line: number;
            /** Reason */
            reason: string;
        };
        /** RejectRequest */
        RejectRequest: {
            /** Ids */
            ids: string[];
            /** Reason */
            reason: string;
            /**
             * Reason Code
             * @description Structured reason; the daily run learns from it
             */
            reason_code?: ("TRUCK_UNAVAILABLE" | "STORE_CLOSED" | "ALREADY_COVERED" | "ROUTE_TOO_SLOW" | "OTHER") | null;
        };
        /** RowsBody */
        RowsBody: {
            /** Mapping */
            mapping?: {
                [key: string]: string;
            } | null;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /** StoreForecast */
        StoreForecast: {
            /** As Of */
            as_of: string | null;
            /** Products */
            products: components["schemas"]["ProductForecast"][];
            store: components["schemas"]["StoreSummary"];
            /** Weather */
            weather: components["schemas"]["WeatherDay"][];
            /**
             * Weather Source
             * @description demo means a demo storm is placed on this forecast's weather
             * @default live
             * @enum {string}
             */
            weather_source: "live" | "demo";
        };
        /** StoreNote */
        StoreNote: {
            /** Store */
            store: string;
            /** Text */
            text: string;
        };
        /** StoreSummary */
        StoreSummary: {
            /** City */
            city: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Readiness
             * @description Share of products with enough cover for the storm window, 0 to 100
             * @default 0
             */
            readiness: number;
            /**
             * Readiness Label
             * @description Ready, Watch or At risk
             * @default
             */
            readiness_label: string;
            /** Region */
            region: string;
            /** Running Low */
            running_low: number;
            /**
             * Storm Days
             * @description Forecast days with a storm or heavy rain
             * @default 0
             */
            storm_days: number;
        };
        /** StormDeskPlan */
        StormDeskPlan: {
            /** Answered */
            answered: boolean;
            /**
             * Debate
             * @description How the three roles arrived at the plan
             */
            debate?: components["schemas"]["DebateTurn"][];
            /** Message */
            message?: string | null;
            /**
             * Plan
             * @description The plan, one sentence per item
             */
            plan?: string[];
            /**
             * Steps
             * @description What storm desk checked, in order
             */
            steps?: components["schemas"]["DeskStep"][];
            /**
             * Transfers
             * @description Pending transfers the plan refers to
             */
            transfers?: components["schemas"]["Transfer"][];
        };
        /** StormDeskRequest */
        StormDeskRequest: {
            /** Goal */
            goal: string;
        };
        /** StormDraft */
        StormDraft: {
            /** Approved */
            approved: number;
            /** Co2 Kg */
            co2_kg: number;
            /** Created At */
            created_at: string;
            /** Decided At */
            decided_at: string | null;
            /** Decided By */
            decided_by: string | null;
            /** Id */
            id: string;
            /** Markdowns Open */
            markdowns_open: number;
            /** Moves */
            moves: components["schemas"]["DraftMove"][];
            /**
             * Onset
             * Format: date
             */
            onset: string;
            /** Protected Usd */
            protected_usd: number;
            /** Rejected */
            rejected: number;
            /** Source */
            source: string;
            /**
             * Status
             * @description draft until a planner decides, then decided
             */
            status: string;
            /**
             * Store Notes
             * @description Draft notes for store managers. Not sent: store email addresses are not set up.
             */
            store_notes: components["schemas"]["StoreNote"][];
            /** Stores */
            stores: string[];
            /** Storm */
            storm: string;
            /** Weekday */
            weekday: string;
        };
        /** TimelineEvent */
        TimelineEvent: {
            /** Actor */
            actor: string;
            /** At */
            at: string;
            /** Detail */
            detail: string;
            /** Kind */
            kind: string;
        };
        /** Transfer */
        Transfer: {
            /**
             * Co2 Kg
             * @description Estimated kg CO2e for the move. See carbon.py for the assumptions.
             * @default 0
             */
            co2_kg: number;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "High" | "Medium" | "Low";
            /** Created At */
            created_at: string | null;
            /** Decided At */
            decided_at?: string | null;
            /** Decided By */
            decided_by?: string | null;
            /** Distance Miles */
            distance_miles: number;
            from_store: components["schemas"]["Ref"];
            /** Headline */
            headline: string;
            /** Id */
            id: string;
            /** Note */
            note?: string | null;
            product: components["schemas"]["ProductRef"];
            /** Qty */
            qty: number;
            /** Reason */
            reason: string;
            /** Runs Low Day */
            runs_low_day: string | null;
            /** Sales Protected Usd */
            sales_protected_usd: number;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "APPROVED" | "REJECTED";
            to_store: components["schemas"]["Ref"];
            /**
             * Urgency
             * @enum {string}
             */
            urgency: "URGENT" | "NORMAL";
        };
        /** UploadBody */
        UploadBody: {
            /**
             * Csv
             * @description The whole CSV file as text, with the column names on the first line
             */
            csv?: string | null;
            /**
             * Mapping
             * @description Your column name for each StormSense column, if the names differ
             */
            mapping?: {
                [key: string]: string;
            } | null;
            /**
             * Xlsx Base64
             * @description An Excel file (.xlsx), base64 encoded. Columns are matched by name
             */
            xlsx_base64?: string | null;
        };
        /** UploadResult */
        UploadResult: {
            /** Feed */
            feed: string;
            /** Ignored Columns */
            ignored_columns: string[];
            /** Kept */
            kept: number;
            /** Message */
            message: string;
            /** Missing Columns */
            missing_columns: string[];
            /**
             * Refusals
             * @description The first 20 refused rows, with the line number and the reason
             */
            refusals: components["schemas"]["Refusal"][];
            /** Refused */
            refused: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeatherAlert */
        WeatherAlert: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Detail */
            detail: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "storm" | "heavy_rain" | "heat";
            /** Stores */
            stores: string[];
            /** Title */
            title: string;
            /** Weekday */
            weekday: string;
        };
        /** WeatherDay */
        WeatherDay: {
            /** Condition */
            condition: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Label */
            label: string;
            /** Rain In */
            rain_in: number;
            /** Temp Max F */
            temp_max_f: number;
            /** Weekday */
            weekday: string;
            /** Wind Max Mph */
            wind_max_mph: number;
        };
        /** WhatIfRequest */
        WhatIfRequest: {
            /**
             * Days
             * @description How many days the storm lasts
             */
            days: number;
            /** Region */
            region?: ("Florida" | "Texas" | "California") | null;
            /**
             * Start Day
             * @description 0 means tomorrow
             */
            start_day: number;
            /**
             * Strength
             * @description How strong the storm is, 0 to 100
             */
            strength: number;
        };
        /** WhatIfResult */
        WhatIfResult: {
            /** Answered */
            answered: boolean;
            /**
             * Extra Demand Units
             * @default 0
             */
            extra_demand_units: number;
            /**
             * Extra Lost Usd
             * @default 0
             */
            extra_lost_usd: number;
            /** Message */
            message?: string | null;
            /**
             * Normal Units
             * @default 0
             */
            normal_units: number;
            plan_change?: components["schemas"]["PlanChange"] | null;
            /** Rows */
            rows?: components["schemas"]["WhatIfRow"][];
            /** Sentence */
            sentence?: string | null;
            /**
             * Stock To Move Units
             * @default 0
             */
            stock_to_move_units: number;
            /**
             * Storm Units
             * @default 0
             */
            storm_units: number;
            /** Window */
            window?: string | null;
        };
        /** WhatIfRow */
        WhatIfRow: {
            /** Extra Lost Usd */
            extra_lost_usd: number;
            /** Normal Units */
            normal_units: number;
            /** On Hand */
            on_hand: number;
            /** Product */
            product: string;
            /** Store */
            store: string;
            /** Storm Units */
            storm_units: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analysis_charts_api_analysis_charts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ask_api_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_api_backtest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestStorm"][];
                };
            };
        };
    };
    briefing_api_briefing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Briefing"];
                };
            };
        };
    };
    demo_alert_api_demo_alert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoAlertResult"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: {
                deep?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transfer"][];
                };
            };
        };
    };
    impact_api_impact_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Impact"];
                };
            };
        };
    };
    analysis_api_ingest_analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
        };
    };
    upload_charts_route_api_ingest_charts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    upload_checks_api_ingest_checks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecksResult"];
                };
            };
        };
    };
    load_demo_api_ingest_demo_load_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    scan_drop_now_api_ingest_drop_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DropResult"];
                };
            };
        };
    };
    get_economics_api_ingest_economics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EconomicsBody"];
                };
            };
        };
    };
    set_economics_api_ingest_economics_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EconomicsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EconomicsBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feeds_api_ingest_feeds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedInfo"][];
                };
            };
        };
    };
    clear_api_ingest_feeds__feed__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feed: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_ingest_feeds__feed__preview_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                feed: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rows_in_api_ingest_feeds__feed__rows_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feed: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RowsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    template_xlsx_api_ingest_feeds__feed__template_xlsx_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feed: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_ingest_feeds__feed__upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feed: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_plan_api_ingest_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanStatus"];
                };
            };
        };
    };
    plan_status_api_ingest_plan_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanStatus"];
                };
            };
        };
    };
    inventory_api_inventory_get: {
        parameters: {
            query?: {
                status?: ("RUNNING_LOW" | "EXTRA") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    loads_api_loads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loads"];
                };
            };
        };
    };
    markdowns_api_markdowns_get: {
        parameters: {
            query?: {
                weather?: "live" | "demo";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkdownSuggestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_markdown_api_markdowns_decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkdownDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkdownSuggestion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    overview_api_overview_get: {
        parameters: {
            query?: {
                weather?: "live" | "demo";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    storm_draft_api_response_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StormDraft"];
                };
            };
        };
    };
    storm_draft_get_api_response__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StormDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    storm_decide_api_response__draft_id__decide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StormDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stores_api_stores_get: {
        parameters: {
            query?: {
                weather?: "live" | "demo";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    store_forecast_api_stores__store_id__forecast_get: {
        parameters: {
            query?: {
                weather?: "live" | "demo";
            };
            header?: never;
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreForecast"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    storm_desk_api_storm_desk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StormDeskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StormDeskPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transfers_api_transfers_get: {
        parameters: {
            query?: {
                status?: ("PENDING" | "APPROVED" | "REJECTED") | null;
                urgency?: ("URGENT" | "NORMAL") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transfer"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_transfers_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_transfers_api_transfers_export_get: {
        parameters: {
            query?: {
                status?: ("PENDING" | "APPROVED" | "REJECTED") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_transfers_reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transfer_api_transfers__transfer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transfer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transfer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    what_if_api_what_if_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatIfRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatIfResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
