"""What the API needs from a data source. Rows are plain dicts keyed like the StormSense tables."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol

Row = dict[str, Any]


@dataclass
class AskResult:
    answered: bool
    answer: str
    columns: list[str] | None = None
    rows: list[list[Any]] | None = None


@dataclass
class Decision:
    changed: list[str]
    skipped: list[str]


class DataSource(Protocol):
    def ping(self) -> None: ...
    def user(self, email: str) -> Row | None: ...
    def stores(self) -> list[Row]: ...
    def products(self) -> list[Row]: ...
    def setting(self, key: str) -> str | None: ...
    def transfers(self, status: str | None, urgency: str | None, limit: int = 500) -> list[Row]: ...
    def transfer(self, rec_id: str) -> Row | None: ...
    def history(self, limit: int = 200) -> list[Row]: ...
    def predictions(self, store_id: str) -> list[Row]: ...
    def gaps(self, store_id: str | None, status: str | None) -> list[Row]: ...
    def backtest(self) -> list[Row]: ...
    def precedents(self, source_id: str, dest_id: str, product_id: str) -> list[Row]: ...
    def weather(self, store_id: str | None) -> list[Row]: ...
    def decide(self, action: str, ids: list[str], actor: str, note: str | None, request_id: str,
               reason_code: str | None = None) -> Decision: ...
    def ask(self, question: str) -> AskResult: ...
